### PR TITLE
Fix us flag

### PR DESCRIPTION
**Pull request by Nushio**
Hi there!

I really liked the svelte-tel-input plugin, but I think the US Flag looks a bit weird with the one giant star. 

I am not an artist, but I spent about an hour trying out several things on Gimp, and this is the one I'm mostly satisfied with.

It matches the art style of the other flags with stars, it doesn't actually have all stars (It's pretty hard to make it look right at that size), but at least at 100% size, it does resemble the US Flag. 

Comments and feedback are welcome. 

Thanks!

Screenshot 2023-05-10 at 10 36 47 PM
Screenshot 2023-05-10 at 10 36 42 PM
Screenshot 2023-05-10 at 10 36 39 PM
Screenshot 2023-05-10 at 10 36 34 PM

### CODE REVIEW

**Comment by gyurielf** [comment]
Hey @Nushio !

Yep, it's much more representative.
Thanks for the PR.

**Comment by Nushio** [comment]
Thank you!

**Comment by Nushio** [comment]
I think the reason the deployment release failed is because I didn't touch the version number.

**Comment by gyurielf** [comment]
It has been released, thy once more.

**Pull request merged**
