### PR TITLE
fix: svlete build

### PR DESCRIPTION
**Pull request by davidonet**

### CODE REVIEW

**Comment by gyurielf** [comment]
Hey! What was the purpose of this PR ?

**Comment by davidonet** [comment]
There is a problem with this line : https://github.com/gyurielf/svelte-tel-input/blob/d1fa7b5478a114a655a1423d4ba08c63d8929b8c/package.json#L161
that prevent building we just need to remove it to be able to build a static website.
So if you don't need it, I think it will help a lot of people to remove it.
No need to merge our PR

**Comment by gyurielf** [comment]
Hey!
Fortunately I implemented this already in my next RC.
It's almost done and simplify and improve a lot of things.
I'll done with in this week.

Thanks for the PR.

**Comment by davidonet** [comment]
Thank you for providing this great and useful component.

**Pull request closed without merging**
